12 authorization
ksilex/qna pull request #10
Opened 2021-04-06 19:44 UTC by ksilex

2021-04-07 09:01 UTC, vkurennov requested changes

2021-04-07 09:01 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  authorize_resource
ты либо вызываешь `authorize_resource`,  либо `autorize!` в каждом экшене, но ни то и другое вместе, потому что `authorize_resource`   как раз и вызвыает `authorize! `, т.е. сейчас у тебя дважды авторизация выполняется

2021-04-07 09:01 UTC, vkurennov commented on app/controllers/application_controller.rb
> +  rescue_from CanCan::AccessDenied do |exception|
тут нужно еще для js и json формата обработчики написать, т.к. они в фоне, то редирект там смысла не имеет, лучше возвращать 403 статус (forbidden)

2021-04-07 09:01 UTC, vkurennov commented on app/controllers/answers_controller.rb
>    include VotingFeatureForControllers
в консерне надо в экшенах тоже вызвать `authorize!`, потому что там нужно правильный объект в этот метод передавать

2021-04-07 10:04 UTC, ksilex commented on app/controllers/application_controller.rb
> +  rescue_from CanCan::AccessDenied do |exception|
я же этот обработчик еще месяц назад написал, файл под названием 401-handler.js

2021-04-07 10:26 UTC, ksilex commented on app/controllers/answers_controller.rb
>    include VotingFeatureForControllers
у меня проверка на авторство ресурса при голосовании в модели же находится

2021-04-07 17:20 UTC, vkurennov requested changes

2021-04-07 17:20 UTC, vkurennov commented on app/controllers/application_controller.rb
> +      format.json { head :forbidden, content_type: 'text/html' }
зачем контент-тип менять? пришел запрос в json, пусть и уйдет json, тем более, что ответ пустой

2021-04-07 17:20 UTC, vkurennov commented on app/controllers/concerns/voting_feature_for_controllers.rb
> +    # хуже - без оповещения юзера флэш сообщением + нужно переписывать другие тесты на тот же самый функционал
переписвание тестов - вообще не причина, на счет флеш сообщения: у тебя есть обработчик для этих запросов, ты можешь вернуть там сообщение и на клиенте сделать обработчик таких сообщений, который будет выводить флеш. 

так что аргумент не принимается

2021-04-07 17:20 UTC, vkurennov commented on app/controllers/users/sessions_controller.rb
> +  skip_authorization_check
если ты везде скипаешь эту проверку , так убери ее вызов из ApplicationController, правда, тогда есть шанс пропустить где-то авторизацию

2021-04-07 17:20 UTC, vkurennov commented on app/controllers/answers_controller.rb
>    include VotingFeatureForControllers
это разные вещи, одно - валидация, другое -проверка прав.

2021-04-08 08:37 UTC, vkurennov approved these changes

2021-04-09 10:35 UTC, merged